n1 = int(input('Digite um número: '));
n2 = int(input('Digite outro: '));
adicao = n1 + n2;
print('A soma entre {} e {} é igual a: {}'.format(n1, n2, adicao));
subtracao = n1 - n2;
print('A subtração entre {} e {} é igual a: {}'.format(n1,n2,subtracao));
multiplicacao = n1 * n2;
print('A multiplicação entre {} e {} é igual a: {}'.format(n1, n2, multiplicacao));
divisao = n1 / n2;
print('A divisão entre {} e {} é igual a: {}'.format(n1, n2, divisao));
exponenciacao = n1 ** n2;
print('A exponeciação entre {} e {} é igual a: {}'.format(n1, n2, exponenciacao));
divisaoInteira = n1 // n2;
print('A divisão inteira entre {} e {} é igual a: {}'.format(n1, n2, divisaoInteira));
restoDivisao = n1 % n2;
print('O resto da divisão entre, {} e {} é igual a: {}'.format(n1, n2, restoDivisao));